### ISSUE TITLE
Error executing action `purge` on resource 'package[ffmpeg]'

### ISSUE THREAD

**Issue by ironsand** [escapestudios-cookbooks/ffmpeg#21]
I get this error all the time when I run `ffmpeg` recipe.
Actually I haven't problem with install and update ffmpeg, but I'll be happier if I don't need to see the error every time.

```
Recipe: ffmpeg::source
  * package[ffmpeg] action purge[2015-01-12T23:21:21+00:00] ERROR: package[ffmpeg] (ffmpeg::source line 13) had an error: ffmpeg has no candidate in the apt-cache; ignore_failure is set, continuing

================================================================================
Error executing action `purge` on resource 'package[ffmpeg]'
================================================================================


Chef::Exceptions::Package
-------------------------
ffmpeg has no candidate in the apt-cache


Resource Declaration:
---------------------
# In /home/vagrant/chef-solo/cookbooks-3/ffmpeg/recipes/source.rb

 13:   package pkg do
 14:     action :purge
 15:     ignore_failure true
 16:   end
 17: end



Compiled Resource:
------------------
# Declared in /home/vagrant/chef-solo/cookbooks-3/ffmpeg/recipes/source.rb:13:in `block in from_file'

package("ffmpeg") do
  action [:purge]
  ignore_failure true
  retries 0
  retry_delay 2
  package_name "ffmpeg"
  cookbook_name :ffmpeg
  recipe_name "source"
end
```

Thanks.

**Comment by djoos** [comment]
Hi @ironsand,

would you be able to let me know which OS and chef-client version you're running?
I'd like to try and get the issue replicated...

Thanks in advance!

Kind regards,
David

**Comment by JustinAiken** [comment]
I get this on Chef 11.6.2 on all manner of debian based; Ubuntu 14.04 is what I'm using now, and see it every run.

**Comment by djoos** [comment]
Hi @JustinAiken and @ironsand,

hmmm, "[Is FFmpeg missing from the official repositories in 14.04?](http://askubuntu.com/questions/432542/is-ffmpeg-missing-from-the-official-repositories-in-14-04)"

Could you please give version 0.4.4 of the cookbook a try?
Thanks in advance for your feedback!

Kind regards,
David

**Comment by ironsand** [comment]
I confirmed there is no error anymore, Thanks!

**Comment by djoos** [comment]
Perfect, thanks for your feedback @ironsand!

Kind regards,
David

**Comment by JustinAiken** [comment]
Yep, that fixes it! Thanks :)
