### ISSUE TITLE
Libx264

### ISSUE THREAD

**Issue by pollosp** [escapestudios-cookbooks/ffmpeg#22]
Hi, in Debían Jessie we have needed pkg-config.deb in order to link Libx264 headers.

**Comment by djoos** [comment]
Hi @pollosp,

I'm going to reference #4 in this thread as IMO libx264 shouldn't stay "baked" into the ffmpeg cookbook...

Kind regards,
David

**Comment by pollosp** [comment]
:+1:  thanks for your answer and your work.
